jwt:
  signing-key: Commander
  expires-time: 604800
  buffer-time: 86400
mysql:
  path: 127.0.0.1:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: self-discipline
  username: root
  password: root
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: true
  log-zap: ""
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
system:
  mode: debug                 # debug, release, test
  addr: 8800
  pprof: false
  promhttp: false
  rate: true
  max-burstSize: 100000
  oss-type: 'qiniu'    # 控制oss选择走本期还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
zap:
  level: info
  format: console
  prefix: '[SELF-DISCIPLINE]'
  director: log
  link-name: latest_log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
qiniu:
  zone: 'ZoneHuanan'
  bucket: 'fiery'
  img-path: 'cdn.fiery.work'
  use-https: false
  access-key: 'eK7YBltAOu1Px-Uk9rQtrSKevRD_t7hfiX_UI5px'
  secret-key: 'NkFhRSrrs9dLQR2Y07Mi8tLkIOGaIgmqAUqm5TT3'
  use-cdn-domains: false
