jwt:
  signing-key: Commander
  expires-time: 604800
  buffer-time: 86400
mysql:
  path: 47.119.117.56:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: self-discipline
  username: root
  password: self-discipline
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: true
  log-zap: ""
redis:
  db: 0
  addr: 47.119.117.56:6379
  password: "123qwe123"
system:
  mode: release                 # debug, release, test
  addr: 8800
  pprof: false
  promhttp: false
  rate: true
  max-burstSize: 100000
  use-multipoint: false
zap:
  level: info
  format: console
  prefix: '[SELF-DISCIPLINE]'
  director: log
  link-name: latest_log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
