basePath: /
info:
  contact: {}
  description: This is a sample Server pets
  title: Swagger Example API
  version: 0.0.1
paths:
  /v1/Register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 密码
        in: formData
        name: password
        type: string
      - description: 手机号码
        in: formData
        name: phone
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"注册成功"}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - Base
  /v1/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 密码
        in: formData
        name: password
        type: string
      - description: 手机号码
        in: formData
        name: phone
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - Base
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
